[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://priday-farelya-workspace-9drive.tose.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
